import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// The real signing key, if this machine has been given one.
//
// android/key.properties is gitignored (it always was — see android/.gitignore,
// which also refuses *.jks and *.keystore) and holds four lines: storeFile,
// storePassword, keyAlias, keyPassword. It is not in the repository and no
// keystore is either; the operator creates both once, on the build machine, and
// keeps the keystore somewhere it can be recovered from.
//
// Absent, the build still works and still signs with the debug key, exactly as
// it did before. That fallback is not there out of politeness: every developer
// and every CI checkout would otherwise fail to produce a release build at all,
// and a mechanism people have to switch off to get their work done gets
// switched off.
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        FileInputStream(keystorePropertiesFile).use { load(it) }
    }
}
val hasReleaseKeystore = keystorePropertiesFile.exists()

android {
    namespace = "com.kurdistanstudentprotection.ksp"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // Kurdistan Student Protection. Each flavour suffixes this, so the five
        // audiences can sit on one phone at once.
        //
        // Changed from com.edupulse.student_app during the rebrand. Android
        // treats a new id as a different app, so an existing install has to be
        // removed rather than upgraded — done now, while that costs one
        // uninstall, because an id that reaches Play is fixed for the life of
        // the listing.
        applicationId = "com.kurdistanstudentprotection.ksp"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName

    }

    // One codebase, five apps. Each audience gets its own applicationId so all
    // of them can sit on one phone at once — which is what a school actually
    // needs when it is testing, and what a family needs when a parent is also
    // a teacher at the same school.
    flavorDimensions += "role"
    productFlavors {
        create("parent") {
            dimension = "role"
            applicationIdSuffix = ".parent"
            resValue("string", "app_name", "KSP Parent")
        }
        create("student") {
            dimension = "role"
            applicationIdSuffix = ".student"
            resValue("string", "app_name", "KSP Student")
        }
        create("teacher") {
            dimension = "role"
            applicationIdSuffix = ".teacher"
            resValue("string", "app_name", "KSP Teacher")
        }
        create("driver") {
            dimension = "role"
            applicationIdSuffix = ".driver"
            resValue("string", "app_name", "KSP Driver")
        }
        create("admin") {
            dimension = "role"
            applicationIdSuffix = ".admin"
            resValue("string", "app_name", "KSP Admin")
        }
    }

    signingConfigs {
        if (hasReleaseKeystore) {
            create("release") {
                storeFile = file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            // The APKs that have shipped so far are signed with the DEBUG key —
            // CN=Android Debug, password "android", generated by whichever
            // laptop happened to build them and held in no secret store. It
            // cannot be rotated, it cannot be backed up by anyone but the
            // person holding that machine, and if it is lost every install on
            // every handset has to be uninstalled by hand before an update will
            // go on. Play will not accept it either, which is why these go out
            // over Telegram.
            //
            // With key.properties present the release build is signed properly.
            // Without it nothing changes and the debug key is used, so a
            // developer's `flutter run --release` and anyone's fresh checkout
            // keep working.
            //
            // Note for whoever switches this on: an APK signed with a different
            // key is not an upgrade of the one already installed. Android
            // refuses it outright, so every existing install has to be removed
            // first. That is a one-time cost and it only gets larger.
            signingConfig = if (hasReleaseKeystore) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
}

flutter {
    source = "../.."
}
